//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropBoxBrowser.MonoDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int LoginBtnLogin = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int LoginEditPwd = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int LoginEditUser = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int MainInfo = 2130968579;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int login = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int main = 2130837505;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int login_name = 2130903041;
			
			private String()
			{
			}
		}
	}
}
