// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DropBoxBrowser.iPhone {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("LoginWindow")]
	public partial class LoginWindow {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_LoginButton;
		
		private MonoTouch.UIKit.UITextField __mt_PasswordLabel;
		
		private MonoTouch.UIKit.UITextField __mt_UserNameLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("LoginButton")]
		private MonoTouch.UIKit.UIButton LoginButton {
			get {
				this.__mt_LoginButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("LoginButton")));
				return this.__mt_LoginButton;
			}
			set {
				this.__mt_LoginButton = value;
				this.SetNativeField("LoginButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("PasswordLabel")]
		private MonoTouch.UIKit.UITextField PasswordLabel {
			get {
				this.__mt_PasswordLabel = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("PasswordLabel")));
				return this.__mt_PasswordLabel;
			}
			set {
				this.__mt_PasswordLabel = value;
				this.SetNativeField("PasswordLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("UserNameLabel")]
		private MonoTouch.UIKit.UITextField UserNameLabel {
			get {
				this.__mt_UserNameLabel = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("UserNameLabel")));
				return this.__mt_UserNameLabel;
			}
			set {
				this.__mt_UserNameLabel = value;
				this.SetNativeField("UserNameLabel", value);
			}
		}
	}
}
