//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.0.3.261")]
[assembly: AssemblyFileVersion("1.0.3.261")]
[assembly: AssemblyTitle("SharpBox")]
[assembly: AssemblyDescription("SharpBox - A cloud storage API")]
[assembly: AssemblyCompany("sharpbox.codeplex.com")]
[assembly: AssemblyCopyright("Copyright (c) 2010 - 2011 Dirk Eisenberg, Yury Averkiev, Renald Dubus, Jay Ongg")]


